name: Build and Deploy Portfolio

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # --- Budowanie i kopiowanie każdej aplikacji ---
    - name: Build gui-v1
      working-directory: gui (React18) v1
      run: |
        npm ci
        npm run build
    - name: Copy gui-v1 build to docs
      run: |
        mkdir -p docs/gui-v1
        cp -r "gui (React18) v1/build/." docs/gui-v1/

    - name: Build gui-v2
      working-directory: gui (React18) v2
      run: |
        npm ci
        npm run build
    - name: Copy gui-v2 build to docs
      run: |
        mkdir -p docs/gui-v2
        cp -r "gui (React18) v2/build/." docs/gui-v2/

    # --- Deploy do GitHub Pages ---
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
